version: 0.2

phases:
  pre_build:
    commands:
      - echo $DEMO_VARIABLE
  build:
    commands:
      - cd services/abraxas-tasks-api/container/
      - ./build.sh mass90/demo-code-deploy
  post_build:
    commands:
      - docker push mass90/demo-code-deploy
