Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.50.4"
  config.disksize.size = "50GB"

  # React: Storybook
  config.vm.network "forwarded_port", guest: 9009, host: 9009
  # React Development
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  
  # Mongo Express
  config.vm.network "forwarded_port", guest: 8081, host: 8081
  # MongoDB
  config.vm.network "forwarded_port", guest: 27017, host: 27017

  # Api
  config.vm.network "forwarded_port", guest: 5000, host: 5000

  config.vm.provider "virtualbox" do |v|
    v.memory = 8248
    v.cpus = 4
  end


  config.vm.synced_folder "../", "/home/app"

  config.vm.provision "shell" do |s|
    s.inline = "apt-get update && apt-get install -y build-essential libssl-dev libffi-dev python-dev libbz2-dev"
  end

  config.vm.provision "shell", path: "script-python-install.sh", privileged: false
  config.vm.provision "shell", path: "script-nvm-install.sh", privileged: false
  config.vm.provision "shell", path: "script-docker-install.sh", privileged: true
  config.vm.provision "shell", path: "script-java-install.sh", privileged: true
  config.vm.provision "shell", path: "script-sonar-install.sh", privileged: true

end
